In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# Read the dataset
ufo_data = pd.read_csv('./data/ufos.csv')

ufo_data.head()

,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700.0,45 minutes,This event took place in early fall around 194...,4/27/2004,29.883056,-97.941111
1,10/10/1949 21:00,lackland afb,tx,NaN,light,7200.0,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...,12/16/2005,29.384210,-98.581082
2,10/10/1955 17:00,chester (uk/england),NaN,gb,circle,20.0,20 seconds,Green/Orange circular disc over Chester&#44 En...,1/21/2008,53.200000,-2.916667
3,10/10/1956 21:00,edna,tx,us,circle,20.0,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.978333,-96.645833
4,10/10/1960 20:00,kaneohe,hi,us,light,900.0,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.418056,-157.803611

In [3]:
ufo_data = pd.DataFrame(
    {'Seconds': ufo_data['duration (seconds)'],
     'Country': ufo_data['country'],
     'Latitude': ufo_data['latitude'],
     'Longitude': ufo_data['longitude']
     }
)

ufo_data.Country.unique()

#ufo_data.head()

array(['us', nan, 'gb', 'ca', 'au', 'de'], dtype=object)

In [4]:
ufo_data.head()

   Seconds Country   Latitude   Longitude
0   2700.0      us  29.883056  -97.941111
1   7200.0     NaN  29.384210  -98.581082
2     20.0      gb  53.200000   -2.916667
3     20.0      us  28.978333  -96.645833
4    900.0      us  21.418056 -157.803611

In [ ]:
# Save new dataframe to a new CSV file
ufo_data.to_csv('./data/ufos_cleaned.csv', index=False)

In [6]:
# Drop Null values and keeping sightings between 1-60 seconds
ufo_data.dropna(inplace=True)

ufo_data = ufo_data[(ufo_data['Seconds'] >= 1) & (ufo_data['Seconds'] <= 60)]

ufo_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25863 entries, 2 to 80330
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Seconds    25863 non-null  float64
 1   Country    25863 non-null  object
 2   Latitude   25863 non-null  float64
 3   Longitude  25863 non-null  float64
dtypes: float64(3), object(1)
memory usage: 1010.3+ KB

In [ ]:
# Encode the 'Country' column using LabelEncoder  
from sklearn.preprocessing import LabelEncoder
 
ufo_data['Country'] = LabelEncoder().fit_transform(ufo_data['Country'])

ufo_data.head()

    Seconds  Country   Latitude   Longitude
2      20.0        3  53.200000   -2.916667
3      20.0        4  28.978333  -96.645833
14     30.0        4  35.823889  -80.253611
23     60.0        4  45.582778 -122.352222
24      3.0        3  51.783333   -0.783333

In [9]:
from altair import Y
from sklearn.model_selection import train_test_split

# Features needed for prediction
selected_features = ['Seconds', 'Latitude', 'Longitude']    

X = ufo_data[selected_features]
y = ufo_data['Country']  # Target variable 

# Split the dataset into training and testing sets(80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [10]:
# Train a Logistic Regression model
from pyexpat import model

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

model = LogisticRegression()
model.fit(X_train, y_train)

predictions = model.predict(X_test)

print(classification_report(y_test, predictions))
print('Predicted labels: ', predictions)
print('Accuracy: ', accuracy_score(y_test, predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        41
           1       0.82      0.22      0.35       250
           2       1.00      1.00      1.00         8
           3       1.00      1.00      1.00       131
           4       0.96      1.00      0.98      4743

    accuracy                           0.96      5173
   macro avg       0.96      0.84      0.87      5173
weighted avg       0.96      0.96      0.95      5173

Predicted labels:  [4 4 4 ... 3 4 4]
Accuracy:  0.9601778465107288

c:\Users\Sko\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [15]:
import pickle

model_filename = 'ufo-model.pkl'
pickle.dump(model, open(model_filename,'wb'))

model = pickle.load(open('ufo-model.pkl','rb'))
print(model.predict([[50,44,-11]]))

[1]

c:\Users\Sko\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(